Repository PinsterTeam/Frontend, pull requests merged in 2018-05, with the labels that each got.

#6 Moser initial prototype merge
  .eslintrc.json
  package-lock.json
  package.json
  public/index.html
  src/components/App.js
  src/components/Header.js
  src/components/Login.js
  src/components/Modal.js
  src/components/NavBar.js
  src/components/Pin.js
  src/components/Router.js
  src/components/Tag.js
  src/components/svg/SvgClose.js
  src/components/svg/SvgCollections.js
  src/components/svg/SvgHome.js
  src/components/svg/SvgRaccoon.js
  src/components/svg/SvgSearch.js
  src/components/svg/SvgSettings.js
  src/css/main.min.css
  src/index.js
Labels: enhancement

#11 Moser sass webpack
  .gitignore
  .sass-lint.yml
  package-lock.json
  package.json
  src/components/App.js
  src/css/App.css
  src/css/App.scss
  src/css/components/_auth-link.scss
  src/css/components/_footer-nav.scss
  src/css/components/_form-group.scss
  src/css/components/_global-search.scss
  src/css/components/_header-util.scss
  src/css/components/_large-header.scss
  src/css/components/_login-splash.scss
  src/css/components/_nav-icon.scss
  src/css/components/_pin-collection.scss
  src/css/components/_pin-list-item.scss
  src/css/components/_pin-modal-content.scss
  src/css/components/_pin-modal-img.scss
  src/css/components/_pin-modal-thumbs.scss
  src/css/components/_pin-modal-viewer.scss
  src/css/components/_pin-modal.scss
  src/css/components/_pin-stack.scss
  src/css/elements/_article.scss
  src/css/elements/_body.scss
  src/css/elements/_button.scss
  src/css/elements/_footer.scss
  src/css/elements/_form.scss
  src/css/elements/_header.scss
  src/css/elements/_img.scss
  src/css/elements/_inputs.scss
  src/css/elements/_links.scss
  src/css/elements/_lists.scss
  src/css/elements/_main.scss
  src/css/elements/_section.scss
  src/css/elements/_svg.scss
  src/css/elements/_typography.scss
  src/css/elements/_video.scss
  src/css/generic/_container.scss
  src/css/generic/_grid.scss
  src/css/generic/_reset.scss
  src/css/generic/_svg-colors.scss
  src/css/index.css
  src/css/main.min.css
  src/css/settings/_colors.scss
  src/css/settings/_variables.scss
  src/css/tools/_keyframes.scss
  src/css/tools/_mixins.scss
  src/css/utilities/_animations.scss
  src/css/utilities/_bg-image.scss
  src/css/utilities/_helpers.scss
  src/css/utilities/_with-divider.scss
  src/index.js
Labels: enhancement, refactor

#12 Add serverless configuration
  .gitignore
  package-lock.json
  package.json
  serverless.yml
Labels: enhancement

#13 Moser ci deploy
  .circleci/config.yml
Labels: enhancement

#27 Newell/fucked collections
  .circleci/config.yml
  .editorconfig
  .eslintrc.json
  package-lock.json
  package.json
  public/index.html
  src/components/App.js
  src/components/Collection.js
  src/components/CollectionPage.js
  src/components/Header.js
  src/components/Home.js
  src/components/Image.js
  src/components/Loader.js
  src/components/Modal.js
  src/components/MyCollections.js
  src/components/NavBar.js
  src/components/Pin.js
  src/components/PinDetails.js
  src/components/PinPage.js
  src/components/Router.js
  src/components/Tag.js
  src/css/App.scss
  src/css/components/_footer-nav.scss
  src/css/components/_form-modal.scss
  src/css/components/_global-search.scss
  src/css/components/_header-nav.scss
  src/css/components/_large-header.scss
  src/css/components/_loader.scss
  src/css/components/_login-splash.scss
  src/css/components/_modal-overlay.scss
  src/css/components/_pin-list-item.scss
  src/css/components/_pin-modal.scss
  src/css/components/_pin-page.scss
  src/css/settings/_variables.scss
  src/css/tools/_keyframes.scss
  src/css/utilities/_bg-image.scss
  src/registerServiceWorker.js
  src/tests/Home.test.js
Labels: enhancement, refactor

#29 Mmoser/load more style
  src/components/CollectionPage.js
  src/components/Home.js
  src/components/Image.js
  src/css/components/_loader.scss
Labels: enhancement

#41 Newell/cache control
  .circleci/config.yml
Labels: bugfix

#45 sample add/remove buttons
  src/components/BtnIncrement.js
  src/components/svg/SvgMinus.js
  src/components/svg/SvgPlus.js
  src/css/App.scss
  src/css/components/_btn-small-round.scss
  src/css/generic/_svg-colors.scss
  src/css/settings/_variables.scss
Labels: enhancement

#47 Moser oauth
  public/img/landing-image.png
  src/components/AuthRedirect.js
  src/components/CollectionPage.js
  src/components/Login.js
  src/components/MyCollections.js
  src/components/PinPage.js
  src/components/Router.js
  src/components/Settings.js
Labels: enhancement

#48 login page is now not scrolling, in a ghetto way. i'm sorry mark
  package-lock.json
  package.json
  src/css/components/_login-splash.scss
Labels: bug, bugfix, enhancement

#53 Newell/base url
  .circleci/config.yml
  .env
  src/components/CollectionPage.js
  src/components/Header.js
  src/components/Home.js
  src/components/Login.js
  src/components/MyCollections.js
  src/components/PinPage.js
  src/components/Settings.js
  src/components/SettingsForm.js
Labels: enhancement

#56 legal page
  src/components/CollectableModal.js
  src/components/Legal.js
  src/components/Login.js
  src/components/Router.js
  src/css/components/_auth-link.scss
Labels: enhancement

#61 Newell/headers
  .gitignore
  src/components/CollectableModal.js
  src/components/GlobalSearch.js
  src/components/HeaderNav.js
  src/components/Home.js
  src/components/Settings.js
  src/components/svg/SvgAngleLeft.js
  src/components/svg/SvgEllipse.js
  src/css/components/_header-nav.scss
  src/css/utilities/_settings-page.scss
Labels: enhancement

#66 Newell/image upload
  .circleci/config.yml
  package.json
  src/components/CreatePin.js
  src/components/Help.js
  src/components/Legal.js
  src/components/Router.js
  src/css/components/_header-nav.scss
  src/css/elements/_article.scss
Labels: enhancement

#67 Jmoser add collections
  package-lock.json
  package.json
  src/components/AuthRedirect.js
  src/components/CollectableDetails.js
  src/components/CollectableModal.js
  src/components/CollectionPage.js
  src/components/CollectionSelectList.js
  src/components/CreateCollectionForm.js
  src/components/HeaderNav.js
  src/components/Home.js
  src/components/LoadMoreButton.js
  src/components/LoadUserData.js
  src/components/Login.js
  src/components/MyCollections.js
  src/components/Router.js
  src/components/Settings.js
  src/components/SettingsForm.js
  src/components/svg/SvgAdd.js
  src/css/components/_pin-list-item.scss
  src/index.js
Labels: bugfix, enhancement

#68 Newell/create pins
  src/components/CreatePin.js
  src/components/HeaderNav.js
  src/components/Router.js
  src/components/Settings.js
Labels: bugfix

#69 Jmoser finish collections
  package-lock.json
  src/components/CollectableDetails.js
  src/components/CollectionSelectList.js
  src/components/LoadUserData.js
Labels: bugfix, enhancement

#71 Every image iss 200x200
  src/components/Image.js
Labels: bugfix

#72 Newell/optional thumbnail
  src/components/Image.js
Labels: bugfix

#73 fixed headers
  src/components/CollectionPage.js
  src/components/MyCollections.js
Labels: bugfix

#74 Jmoser actually finish collections
  src/components/CollectableDetails.js
  src/components/CollectableModal.js
  src/components/CollectionPage.js
  src/components/CollectionSelectList.js
Labels: bugfix, enhancement

#75 fixed header
  src/components/PinPage.js
Labels: bug, bugfix

#79 Jmoser prod tweaks
  src/components/CollectableDetails.js
  src/components/CollectionPage.js
  src/components/CreatePin.js
Labels: bugfix

#85 Finally search is fixed, by refactoring fetch out of collectable list…
  src/components/CollectableListItem.js
  src/components/Home.js
Labels: bugfix

#86 Update _pin-modal-img.scss
  src/css/components/_pin-modal-viewer.scss
Labels: bugfix

#89 thumbnail fancy
  src/components/CollectableDetails.js
  src/components/Image.js
Labels: enhancement

#109 bigger thumbs
  src/components/Image.js
Labels: enhancement
